#!/usr/bin/env /python
#-*- coding:utf-8 -*-

from sqlalchemy import create_engine
from sqlalchemy import text
import pandas as pd
import time
import sys

reload(sys)
sys.setdefaultencoding('utf-8')

class SQL2File(object):
    """执行SQL并将数据导出为一个文件"""
    def __init__(self, username='root', password='root',
                       host='127.0.0.1', port=3306, database='',
                       charset='utf8'):
    
        self.db_conf = {
            'username': username,
            'password': password,
            'host': host,
            'port': port,
            'database': database,
            'charset': charset,
        }

        # 生成数据库连接串
        self.db_str = ('mysql+mysqldb://{username}:{password}@{host}:{port}/{database}'
                       '?charset={charset}'.format(**self.db_conf))
        # 获得连接数据库对象
        self.engine = create_engine(self.db_str)

        self.df = None # 初始化数据结构

    def sql2csv(self, sql='', file_name='/tmp/sql.xls', sql_param=None):
        """执行sql并且导出为Excel
        Args:
            sql: 需要执行的SQL
        """
        self.sql2df(sql = sql)
        self.df.to_csv(file_name)

    def sql2df(self, sql='', sql_param=None):
        """执行sql获得 DataFrame对象
        Args:
            sql: 需要执行的SQL
        """

        self.df = pd.read_sql_query(sql, self.engine)
        return self.df

def main():
    db_conf = {
        'username': 'root',
        'password': 'root',
        'host': '127.0.0.1',
        'port': 3306,
        'database': 'test',
    }

    sql2file = SQL2File(**db_conf)
    
    excel_name = '/tmp/nbuy52db_info_{dt}.csv'.format(dt = str(time.time()))

    sql = '''
SELECT DISTINCT shop_id
FROM keeper_relation_keeper_shop
WHERE keeper_id IN (
    SELECT DISTINCT keeper_id
    FROM keeper_session
    WHERE user_agent LIKE :c
        AND created_at >= '2018-05-27'
    '''

    sql2file.sql2csv(sql = text(sql), file_name = excel_name, sql_param={'c': '%iOS%Napos%'})

if __name__ == '__main__':
   main()
